index page
htmlacademy-adaptive/1585533-sedona-21 pull request #2
Opened 2020-11-13 20:18 UTC by alexshop2017

2020-11-14 19:52 UTC, RomanZharko reviewed
Блок / Элемент / Модификатор (БЭМ). Класс блока для стилей оформления. Класс элемента для стилей позиционирования. Класс модификатора для стилей состояния если у блока есть несколько состояний. Мне подобный подход очень помогает для понимания необходимости того или иного кдасса, в данном проекте это может быль не очевидно. Но если проект разрастается и появляется необходимость переиспользования блоков польза БЭМ становиться очевидной, и лучше уже сейчас придерживаться данного похода. Если возникли дополнительные вопросы задавай в телеграмме.

2020-11-14 19:52 UTC, RomanZharko commented on source/index.html
> +  <body class="page__body">
На этом блоке есть класс элемента но нет класса блока, оформление блока нужно задавать через класс блока, а позиционирование и внешние отступы относительно родительского через класс элемента. Такое разбиение на стили оформления и позиционирования полезно для переиспользования, к примеру тебе в другом месте прийдется использовать какой-то компонент(блок), только с большими отступами и ты просто применишь необходимый класс к которому привяжутся все стили, а отступы добавишь через класс элемента

2020-11-14 19:52 UTC, RomanZharko commented on source/index.html
> +    <header class="page-header">
Здесь напротив есть класс блока но нет класса элемента

2020-11-14 19:52 UTC, RomanZharko commented on source/index.html
> +      <a class="page-header__logo">
Класс элемента без класса блока

2020-11-14 19:52 UTC, RomanZharko commented on source/index.html
> +      <a class="page-header__logo">
Дальше ситуация аналогична

2020-11-16 18:52 UTC, alexshop2017 commented on source/index.html
> +    <header class="page-header">
Добавил блок body

2020-11-16 18:56 UTC, alexshop2017 commented on source/index.html
> +      <a class="page-header__logo">
Лого решил сделать элементом, а не блоком.

2020-11-16 20:09 UTC, RomanZharko requested changes
В остальном все очень хорошо

2020-11-16 20:09 UTC, RomanZharko commented on source/index.html
> +            <a class="social__item social__link--twitter"></a>
здесь будет правильно .social__link .social__link--twitter, так как .social__item это класс тега li, а ссылки нужно обьединить другим классом БЭМ-элемента

2020-11-17 06:57 UTC, merged